# -*- coding: utf-8 -*-
"""
/***************************************************************************
 shapeloader
                                 A QGIS plugin
 Loads a shapefile
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-31
        copyright            : (C) 2020 by linus
        email                : linuswanji14@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load shapeloader class from file shapeloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shape_loader import shapeloader
    return shapeloader(iface)
